#!/usr/bin/env bash

if [ "${PREFIX}_str" == "_str" ]; then
    echo "请先设置PREFIX环境变量"
    exit
fi

export LD_LIBRARY_PATH=$PREFIX/lib
case $1 in
start)
    customerlive_tcp_server -c54574 -r54575 -l$PREFIX/var/log/customerlive.tcp.log -p$PREFIX/var/tmp/customerlive.tcp.pid -t20 -d
    ;;
stop)
    cat $PREFIX/var/tmp/customerlive.tcp.pid |xargs kill
    ;;
restart)
    cat $PREFIX/var/tmp/customerlive.tcp.pid |xargs kill
    customerlive_tcp_server -c54574 -r54575 -l$PREFIX/var/log/customerlive.tcp.log -p$PREFIX/var/tmp/customerlive.tcp.pid -t20 -d
    ;;
*)
    echo "Usage"
    echo "$0 [start|stop|restart]"
    ;;
esac
