/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "job.h"

CORBA_string JobManager__get_FirstName(JobManager _obj, CORBA_Environment *ev){
CORBA_string _ORBIT_retval;
ORBit_c_stub_invoke (_obj, &JobManager__iinterface.methods, 0, &_ORBIT_retval, NULL, NULL, ev, JobManager__classid, G_STRUCT_OFFSET (POA_JobManager__epv, _get_FirstName),
(ORBitSmallSkeleton) _ORBIT_skel_small_JobManager__get_FirstName);

return _ORBIT_retval;
}
CORBA_string JobManager__get_status(JobManager _obj, CORBA_Environment *ev){
CORBA_string _ORBIT_retval;
ORBit_c_stub_invoke (_obj, &JobManager__iinterface.methods, 1, &_ORBIT_retval, NULL, NULL, ev, JobManager__classid, G_STRUCT_OFFSET (POA_JobManager__epv, _get_status),
(ORBitSmallSkeleton) _ORBIT_skel_small_JobManager__get_status);

return _ORBIT_retval;
}
void JobManager__set_status(JobManager _obj, const CORBA_char * value, CORBA_Environment *ev){
gpointer _args[1];
_args[0] = (gpointer)&value;
ORBit_c_stub_invoke (_obj, &JobManager__iinterface.methods, 2, NULL, _args, NULL, ev, JobManager__classid, G_STRUCT_OFFSET (POA_JobManager__epv, _set_status),
(ORBitSmallSkeleton) _ORBIT_skel_small_JobManager__set_status);

}
CORBA_string JobManager_QueryJobStatus(JobManager _obj, const CORBA_long number, CORBA_string* property, CORBA_Environment *ev){
CORBA_string _ORBIT_retval;
gpointer _args[2];
_args[0] = (gpointer)&number;
_args[1] = &property;
ORBit_c_stub_invoke (_obj, &JobManager__iinterface.methods, 3, &_ORBIT_retval, _args, NULL, ev, JobManager__classid, G_STRUCT_OFFSET (POA_JobManager__epv, QueryJobStatus),
(ORBitSmallSkeleton) _ORBIT_skel_small_JobManager_QueryJobStatus);

return _ORBIT_retval;
}
